### PR TITLE
Fix 'acount' typo in Multiplayer.swagger.json

### PR DESCRIPTION
**Pull request by mfoda**

### CODE REVIEW

**Comment by mfoda** [comment]
These typos are still present in the master branch. Am I missing something?

**Comment by pgilmorepf** [comment]
These files are auto generated, so fixing them manually here won't fix the origin of the problem.
They'll get clobbered with the bad values again very quickly.
Thanks for pointing out the issue, I'll find the place they're generated from, and fix it there.

**Comment by pgilmorepf** [comment]
I have submitted a fix to the origin where it's generated.
The fix should make its way through the system soon.

**Comment by mfoda** [comment]
Ah. That makes sense. Thanks for the fix! @pgilmorepf

**Pull request closed without merging**
